volumes:
  postgres-data:

services:
  crm-system-postgres:
    image: postgres:16-bookworm
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: school_db
    restart: unless-stopped
    container_name: crm-system-postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 120s
      timeout: 5s
      retries: 2
      start_period: 30s